import type { Approval } from './types.js';

/**
 * Plain-English rendering of an approval.
 *
 * Every string here is composed from observed fields. Nothing is generated by a
 * model, so the same approval always reads the same way and a user can check
 * each clause against the raw data.
 */

/** Shorten an address for display without losing verifiability at a glance. */
export function shortAddr(addr: string): string {
  if (!addr || addr.length < 12) return addr || '—';
  return `${addr.slice(0, 6)}…${addr.slice(-4)}`;
}

/**
 * Who holds the key. `spenderName` is nullable and, when present, is
 * attacker-controllable text — it is displayed, never interpreted.
 */
export function spenderLabel(a: Pick<Approval, 'spenderName' | 'spender'>): string {
  const name = a.spenderName?.trim();
  if (!name) return shortAddr(a.spender);
  return `${name} ${shortAddr(a.spender)}`;
}

export function usd(n: number): string {
  if (!Number.isFinite(n)) return '$0.00';
  if (n >= 1000) return `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  return `$${n.toFixed(2)}`;
}

/** The condensed reason chain used in the table's WHY column. */
export function why(a: Approval): string {
  return a.reasons.length ? a.reasons.join(' · ') : 'no elevated signals';
}

/**
 * Full, verifiable identity of an approval.
 *
 * Truncated addresses cannot be checked against anything, so anywhere a user
 * might act on this — or an agent might repeat it — the whole address is shown.
 */
export function identity(a: Approval): string[] {
  return [
    `Token    ${a.tokenSymbol}  ${a.tokenContract}`,
    `Spender  ${a.spenderName?.trim() ?? 'unknown'}  ${a.spender}`,
    `Chain    ${a.chainName} (${a.chainId})    Type  ${a.type}`,
  ];
}

/** One-sentence summary of a single approval, used by `explain <id>`. */
export function sentence(a: Approval): string {
  const who = a.spenderName?.trim() || shortAddr(a.spender);
  const scope = a.isUnlimited ? 'unlimited' : a.approvedAmount;
  const parts = [`${who} can spend ${scope} ${a.tokenSymbol} on ${a.chainName}`];
  if (a.exposureUsd > 0) parts.push(`reaching ${usd(a.exposureUsd)} of what you hold today`);
  else parts.push('but you hold none of that token right now');
  return `${parts.join(', ')}.`;
}

/** The headline. This is the line that has to land in the first four seconds. */
export function headline(t: {
  openDoors: number;
  reachableUsd: number;
  critical: number;
  worst: Approval | null;
}): string[] {
  if (t.openDoors === 0) {
    return ['No open doors found — nothing is currently able to spend your tokens without asking.'];
  }
  const door = t.openDoors === 1 ? 'open door' : 'open doors';
  const lines = [
    `${t.openDoors} ${door} · ${usd(t.reachableUsd)} reachable${t.critical ? ` · ${t.critical} critical` : ''}`,
  ];
  if (t.worst) {
    const scope = t.worst.isUnlimited ? 'unlimited' : t.worst.approvedAmount;
    lines.push(
      `Worst: ${scope} ${t.worst.tokenSymbol} to ${t.worst.spenderName?.trim() || 'an unknown contract'} — ${why(t.worst)}`,
    );
  }
  return lines;
}
